/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Eventos.java
 *
 * Created on 07-ene-2012, 15:43:49
 */
package GUI;

import Logica.Categoria;
import Logica.Evento;
import Logica.Logica;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class Eventos extends javax.swing.JFrame {

    /** Creates new form Eventos */
    String categoria;
    
    public Eventos(String categoria) {
        initComponents();
        setLocationRelativeTo(null);
        if (!(Logica.dameLogica().obtenerCategoriaPorString(categoria)
                .getListaEventos().isEmpty()))
            insertarElementos(categoria);
        this.categoria = categoria;
    }

    public void insertarElementos(String cat){
       Categoria categoria = Logica.dameLogica().obtenerCategoriaPorString(cat);
       Iterator iterator = categoria.getListaEventos().iterator();
       int cont = 0;
       DefaultListModel model = new DefaultListModel();
       while(iterator.hasNext()){
           model.add(cont, ((Evento)iterator.next()).getNombre());
       }
       jList1.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Elige el evento en donde quieres apostar");

        jScrollPane1.setViewportView(jList1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<-Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Evento evento = null;
        evento = Logica.dameLogica().obtenerEventoPorString
                ((String)jList1.getSelectedValue(),
                Logica.dameLogica().getIdCategoriaActual());
        Logica.dameLogica().setIdEventoActual(evento.getId());
        System.out.println(Logica.dameLogica().getIdEventoActual());
        if (evento.isAdmiteTabla())
            Persistencia.HiloUSB.dti.setVentana(new ParticipantesVarios(jList1.getModel()
            .getElementAt(jList1.getSelectedIndex()).toString(),categoria));
        else
            Persistencia.HiloUSB.dti.setVentana(new Participantes(jList1.getModel()
            .getElementAt(jList1.getSelectedIndex()).toString(),categoria));            
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Persistencia.HiloUSB.dti.setVentana(new InicioCategoria());
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
