/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParticipantesVarios.java
 *
 * Created on 07-ene-2012, 15:56:33
 */
package GUI;

import Logica.Apuesta;
import Logica.Evento;
import Logica.Logica;
import Logica.Participante;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class ParticipantesVarios extends javax.swing.JFrame {
    
    private ArrayList<String> ranking = new ArrayList<String>(); //Estos son los participantes de la tabla ordenados segun el orden que se muestra
    private String nombre; //Este es el nombre del evento que se recibe en el constructor, deberia guardarse en el init

    /** Creates new form ParticipantesVarios */
    public ParticipantesVarios(String nombre) {
        initComponents();
        this.nombre = nombre;
        setLocationRelativeTo(null);
        if(!(Logica.dameLogica().getEventoPorNombre(nombre).getParticipantes()
                .isEmpty()))
            insertarParticipantes(nombre);
    }

    public void elegirParticipante(){
        String participante = jList1.getModel()
                .getElementAt(jList1.getSelectedIndex()).toString();
        DefaultListModel model = new DefaultListModel();
        DefaultListModel model1 = new DefaultListModel();
        Evento evento = Logica.dameLogica().getEventoPorNombre(nombre);
        Iterator iterator = evento.getParticipantes().iterator();
        int cont = 0;
        while(iterator.hasNext()){
            String elemento = ((Participante)iterator.next()).getNombre();
            if((!elemento.equals(participante))){
                if(!ranking.contains(elemento)){ 
                    model.add(cont, elemento);
                    cont++;
                }
            }
            else
                ranking.add(elemento);
        }
        iterator = ranking.iterator();
        cont = 0;
        while(iterator.hasNext()){
            model1.add(cont, iterator.next());
            cont++;
        }
        jList1.setModel(model);
        jList2.setModel(model1);
    }

    public void retirarParticipante(){
        String participante = jList2.getModel()
                .getElementAt(jList2.getSelectedIndex()).toString();
        DefaultListModel model = new DefaultListModel();
        DefaultListModel model1 = new DefaultListModel();
        Evento evento = Logica.dameLogica().getEventoPorNombre(nombre);
        Iterator iterator = ranking.iterator();
        int cont = 0;
        while(iterator.hasNext()){
            String elemento = (String)iterator.next();
            if((!elemento.equals(participante))){
                    model.add(cont, elemento);
                    cont++;
            }
        }
        ranking.remove(participante);
        iterator = evento.getParticipantes().iterator();
        cont = 0;
        while(iterator.hasNext()){
            String elemento = ((Participante)iterator.next()).getNombre();
            if(!ranking.contains(elemento)){
                model1.add(cont, elemento);
                cont++;
            }
        }
        jList2.setModel(model);
        jList1.setModel(model1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void insertarParticipantes(String nombre){
        Evento evento = Logica.dameLogica().getEventoPorNombre(nombre);
        Iterator iterator = evento.getParticipantes().iterator();
        int cont = 0;
        DefaultListModel model = new DefaultListModel();
        while(iterator.hasNext()){
            model.add(cont, ((Participante)iterator.next()).getNombre());
        }
        jList1.setModel(model);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        apellidoApostador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cedulaApostador = new javax.swing.JTextField();
        montoApuesta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        nombreApostador = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("Elige el número de participantes a los cuales le quieres apostar");

        jLabel5.setText("Monto apuesta");

        jLabel4.setText("Apellido");

        jLabel3.setText("Cédula");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setText("Apostar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        nombreApostador.setText(" ");

        jButton2.setText("<-Volver");

        jButton3.setText("--->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("<---");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(263, 263, 263)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nombreApostador, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(apellidoApostador, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(267, 267, 267)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cedulaApostador, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(montoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton3)
                                .addGap(11, 11, 11)
                                .addComponent(jButton4)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nombreApostador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(apellidoApostador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulaApostador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(montoApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Apostar().setVisible(true);
        this.dispose();
        ArrayList<Participante> participantes = new ArrayList();
        
        //for de todos los participantes seleccionados
        Participante participante = Logica.dameLogica().obtenerParticipantePorString
                ((String)"Leones del Caracas", 
                Logica.dameLogica().getIdEventoActual(), 
                Logica.dameLogica().getIdCategoriaActual());
        
        Participante participante2 = Logica.dameLogica().obtenerParticipantePorString
                ((String)"Cardenales de Lara", 
                Logica.dameLogica().getIdEventoActual(), 
                Logica.dameLogica().getIdCategoriaActual());
        
        participantes.add(participante);
        participantes.add(participante2);
        
        Apuesta apuesta = new Apuesta(nombreApostador.getText(), 
                 apellidoApostador.getText(), 
                 Integer.parseInt(cedulaApostador.getText()), 
                 Integer.parseInt(montoApuesta.getText()), 
                 Logica.dameLogica().getIdEventoActual(),
                 participantes);
        
        Logica.dameLogica().agregarApuesta(apuesta);
        apuesta.guardarApuesta(Logica.dameLogica().getListaApuestas());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        elegirParticipante();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        retirarParticipante();
    }//GEN-LAST:event_jButton4ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoApostador;
    private javax.swing.JTextField cedulaApostador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField montoApuesta;
    private javax.swing.JTextField nombreApostador;
    // End of variables declaration//GEN-END:variables
}
